### ISSUE TITLE
tasty-1.5 not accepted

### ISSUE THREAD

**Issue by ysangkok** [haskellari/lattices#125]
according to CONTRIBUTING.md, I am not making a pull request.

This is the source of the constraint: https://github.com/haskellari/lattices/blob/683f8f88a58e64741f97b48e6d4a4345710ecb15/lattices.cabal#L132

This is the Stackage issue:

* https://github.com/commercialhaskell/stackage/issues/7111

**Comment by phadej** [comment]
As it's just test, I won't make revisions just for them.

**Comment by ysangkok** [comment]
All right, I will be closing this then.
